version: '3'
services: 
  web:
    image: nginx:alpine
    ports:
      - "2080:80"
    volumes:
      - ./data:/data
      - ./storage:/data/storage
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/data/index.html
